
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  - name: postgres-secret
                    key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  - name: postgres-secret
                    key: password
            - name: POSTGRES_DB
              value: inventory
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-storage-data
      volumes:
        - name: postgres-storage-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
